In [1]:
import tensorflow as tf

/Users/olaf/.pyenv/versions/anaconda3/envs/tfp3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
hello = tf.constant('Hello, Tensorflow')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [4]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello, Tensorflow'
[10, 32, 42]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [8]:
x_data = [[1,2,3],[4,5,6]]
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [9]:
expr = tf.matmul(X, W) + b

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-1.816064   -0.41869706]
 [ 1.50114501  1.12412238]
 [-0.77896219 -1.86003709]]
=== b ===
[[-1.20924771]
 [ 0.28632328]]
=== expr ===
[[-2.35990834 -4.95981169]
 [-4.14598131 -6.92807627]]
